export const defaultMenu = [
  {
    id: 1,
    name: 'Classic Espresso',
    description: 'Rich, bold single-origin espresso with a velvety crema',
    price: 3.50,
    category: 'espresso',
    image: '☕',
    popular: true,
  },
  {
    id: 2,
    name: 'Vanilla Latte',
    description: 'Smooth espresso with steamed milk and house-made vanilla syrup',
    price: 5.25,
    category: 'latte',
    image: '🥛',
    popular: true,
  },
  {
    id: 3,
    name: 'Caramel Macchiato',
    description: 'Espresso marked with foamed milk and drizzled with buttery caramel',
    price: 5.75,
    category: 'latte',
    image: '🍮',
    popular: true,
  },
  {
    id: 4,
    name: 'Mocha Delight',
    description: 'Belgian chocolate meets espresso, topped with whipped cream',
    price: 5.50,
    category: 'mocha',
    image: '🍫',
    popular: false,
  },
  {
    id: 5,
    name: 'Cold Brew',
    description: '18-hour slow-steeped for a smooth, naturally sweet finish',
    price: 4.75,
    category: 'cold',
    image: '🧊',
    popular: true,
  },
  {
    id: 6,
    name: 'Chai Tea Latte',
    description: 'Spiced chai blend with steamed oat milk and a hint of honey',
    price: 5.00,
    category: 'tea',
    image: '🍵',
    popular: false,
  },
  {
    id: 7,
    name: 'Matcha Latte',
    description: 'Ceremonial-grade matcha whisked with your choice of milk',
    price: 5.50,
    category: 'tea',
    image: '🍃',
    popular: false,
  },
  {
    id: 8,
    name: 'Americano',
    description: 'Espresso diluted with hot water for a clean, bright cup',
    price: 3.75,
    category: 'espresso',
    image: '☕',
    popular: false,
  },
  {
    id: 9,
    name: 'Cappuccino',
    description: 'Equal parts espresso, steamed milk, and cloud-like foam',
    price: 4.50,
    category: 'espresso',
    image: '☁️',
    popular: true,
  },
  {
    id: 10,
    name: 'Affogato',
    description: 'A scoop of vanilla gelato drowned in hot espresso',
    price: 6.00,
    category: 'specialty',
    image: '🍨',
    popular: false,
  },
  {
    id: 11,
    name: 'Lavender Honey Latte',
    description: 'Floral lavender and wildflower honey with silky steamed milk',
    price: 5.75,
    category: 'specialty',
    image: '💜',
    popular: true,
  },
  {
    id: 12,
    name: 'Iced Coconut Mocha',
    description: 'Chocolate espresso poured over coconut milk and ice',
    price: 5.50,
    category: 'cold',
    image: '🥥',
    popular: false,
  },
]

export const categories = [
  { id: 'all', label: 'All Drinks' },
  { id: 'espresso', label: 'Espresso' },
  { id: 'latte', label: 'Lattes' },
  { id: 'mocha', label: 'Mochas' },
  { id: 'cold', label: 'Cold Drinks' },
  { id: 'tea', label: 'Tea' },
  { id: 'specialty', label: 'Specialty' },
]

export const sizes = [
  { id: 'small', label: 'Small', extra: 0 },
  { id: 'medium', label: 'Medium', extra: 0.75 },
  { id: 'large', label: 'Large', extra: 1.50 },
]

export const milkOptions = [
  { id: 'whole', label: 'Whole Milk', extra: 0 },
  { id: 'oat', label: 'Oat Milk', extra: 0.60 },
  { id: 'almond', label: 'Almond Milk', extra: 0.60 },
  { id: 'coconut', label: 'Coconut Milk', extra: 0.60 },
  { id: 'none', label: 'No Milk', extra: 0 },
]
