export const defaultMenu = [
  {
    id: 1,
    name: 'Klassisk Espresso',
    description: 'Rik, kraftfull single-origin espresso med en sammetslen crema',
    price: 3.50,
    category: 'espresso',
    image: '☕',
    popular: true,
  },
  {
    id: 2,
    name: 'Vanilj Latte',
    description: 'Len espresso med ångad mjölk och hemgjord vaniljsirap',
    price: 5.25,
    category: 'latte',
    image: '🥛',
    popular: true,
  },
  {
    id: 3,
    name: 'Karamell Macchiato',
    description: 'Espresso med mjölkskum och ett drizzle av smörig karamell',
    price: 5.75,
    category: 'latte',
    image: '🍮',
    popular: true,
  },
  {
    id: 4,
    name: 'Mocha Delight',
    description: 'Belgisk choklad möter espresso, toppad med vispgrädde',
    price: 5.50,
    category: 'mocha',
    image: '🍫',
    popular: false,
  },
  {
    id: 5,
    name: 'Cold Brew',
    description: '18 timmars långsam brantning för en len, naturligt söt avslutning',
    price: 4.75,
    category: 'cold',
    image: '🧊',
    popular: true,
  },
  {
    id: 6,
    name: 'Chai Te Latte',
    description: 'Kryddig chai med ångad havremjölk och en hint av honung',
    price: 5.00,
    category: 'tea',
    image: '🍵',
    popular: false,
  },
  {
    id: 7,
    name: 'Matcha Latte',
    description: 'Ceremoniell matcha vispat med valfri mjölk',
    price: 5.50,
    category: 'tea',
    image: '🍃',
    popular: false,
  },
  {
    id: 8,
    name: 'Americano',
    description: 'Espresso utspädd med hett vatten för en ren, frisk kopp',
    price: 3.75,
    category: 'espresso',
    image: '☕',
    popular: false,
  },
  {
    id: 9,
    name: 'Cappuccino',
    description: 'Lika delar espresso, ångad mjölk och molnliknande skum',
    price: 4.50,
    category: 'espresso',
    image: '☁️',
    popular: true,
  },
  {
    id: 10,
    name: 'Affogato',
    description: 'En kula vaniljglass dränkt i het espresso',
    price: 6.00,
    category: 'specialty',
    image: '🍨',
    popular: false,
  },
  {
    id: 11,
    name: 'Lavendel Honung Latte',
    description: 'Blommig lavendel och vildblommshonung med silkeslen ångad mjölk',
    price: 5.75,
    category: 'specialty',
    image: '💜',
    popular: true,
  },
  {
    id: 12,
    name: 'Isad Kokosnöt Mocha',
    description: 'Chokladespresso hälld över kokosmjölk och is',
    price: 5.50,
    category: 'cold',
    image: '🥥',
    popular: false,
  },
]

export const categories = [
  { id: 'all', label: 'Alla Drycker' },
  { id: 'espresso', label: 'Espresso' },
  { id: 'latte', label: 'Lattes' },
  { id: 'mocha', label: 'Mochas' },
  { id: 'cold', label: 'Kalla Drycker' },
  { id: 'tea', label: 'Te' },
  { id: 'specialty', label: 'Specialitet' },
]

export const sizes = [
  { id: 'small', label: 'Liten', extra: 0 },
  { id: 'medium', label: 'Medium', extra: 0.75 },
  { id: 'large', label: 'Stor', extra: 1.50 },
]

export const milkOptions = [
  { id: 'whole', label: 'Helmjölk', extra: 0 },
  { id: 'oat', label: 'Havremjölk', extra: 0.60 },
  { id: 'almond', label: 'Mandelmjölk', extra: 0.60 },
  { id: 'coconut', label: 'Kokosmjölk', extra: 0.60 },
  { id: 'none', label: 'Utan Mjölk', extra: 0 },
]
